# Generated by Django 5.2.7 on 2025-12-05 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateTimeField()),
                ('salario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('producto_suministrado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mcdonalds.clientes')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mcdonalds.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=50)),
                ('fecha_entrega', models.DateTimeField()),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mcdonalds.proveedores')),
            ],
        ),
    ]
